language: generic

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=22.2.1

cache:
  directories:
    - docker-otp-22.2.1

before_install:
  - make docker-setup DOCKER_OTP_VERSION=${OTP_VERSION}

script:
  - make docker-test DOCKER_OTP_VERSION=${OTP_VERSION}
